
#include "defines.c"

#include "level.c"
#include "level_logic.c"
#include "level_timer.c"
#include "level_music.c"

#include "cct.c"
#include "cct_movement.c"

#include "gui.c"
#include "gui_history.c"
#include "gui_messages.c"
#include "gui_player_info.c"
#include "gui_game_effects.c"
#include "gui_level_info.c"

#include "particles.c"
#include "explosion_effect.c"
#include "weapon_effects.c"
#include "weapon_projectile.c"

#include "player.c"
#include "player_camera.c"
#include "player_wpn_logic.c"
#include "player_wpn_knife.c"
#include "player_wpn_pistol.c"
#include "player_wpn_shotgun.c"
#include "player_wpn_chaingun.c"
#include "player_wpn_rocketl.c"
#include "player_behaviour.c"

#include "ai.c"
#include "ai_logic.c"
#include "ai_movement.c"
#include "ai_state_machine.c"
#include "ai_sprite.c"
#include "ai_weapons.c"
#include "ai_update.c"
#include "ai_human_melee.c"
#include "ai_human_pistol.c"
#include "ai_human_shotgun.c"
#include "ai_human_chaingun.c"
#include "ai_human_rocketl.c"

#include "props.c"
#include "props_helper.c"
#include "props_level_end.c"
#include "props_barrel.c"
#include "props_decor.c"
#include "props_door.c"
#include "props_secret.c"
#include "props_switch.c"
#include "props_trigger.c"
#include "props_update.c"

#include "items.c"
#include "items_wpn.c"