/*#########################################################################################################################################################
NEXUS A8 : GAME BUILDER :: By Brian Pressley (Evo) (Evoeon) :::: Creates Pointers for actions and functions :: Lite-C :: 3DGamestudio A8
#########################################################################################################################################################*/


//Generates a header file that holds all action/function pointers for 3D mesh generation
void gen_nxs_pointers()
{
	STRING* gotofile = str_create(work_dir); str_cat(gotofile, "\\code_mesh\\"); SetCurrentDirectory(_chr(gotofile));
	default_handle = file_open_write("nxs_pointers.h");
	
	file_str_write(default_handle, "//Nexus Pointers for actions and functions");next_line();
	file_str_write(default_handle, "//This script is auto-generated by the nexus editor");next_line();next_line();
	file_str_write(default_handle, "float* action_control[600];");next_line();next_line();
	
	file_str_write(default_handle, "void nxs_assign_pointers()");next_line();
	file_str_write(default_handle, "{");next_line();
	
	int _x = 0;
	for (; _x<600; _x++)
	{		
		file_str_write(default_handle, "   action_control[ ");
		file_var_write (default_handle,_x);
		file_str_write(default_handle, "] = ");
		if(!str_cmpi((nxs_actions.pstring)[_x], "EMPTY"))
		{
			file_str_write(default_handle,(nxs_actions.pstring)[_x]); file_str_write(default_handle, ";");
		}
		else{file_str_write(default_handle, "NULL;");}
		next_line();
	}
	file_str_write(default_handle, "}");next_line();
	file_close (default_handle);
	gotofile = str_create(work_dir); SetCurrentDirectory(_chr(gotofile));
}